[project]
name = "Test_pdm"
version = "1"
description = "Default template for PDM package"
authors = [
    {name = "TilNeubauer", email = "nt1703@mci4me.at"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
